AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  HostedZone:
    Type: String
    Description: "Hosted Zone"
    MinLength: 5

  DefaultNSTTL:
    Type: Number
    Description: "Default Name Server TTL in seconds"
    Default: 3600
    MinValue: 60

  DefaultRecordTTL:
    Type: Number
    Description: "Default DNS Record TTL in seconds"
    Default: 3600
    MinValue: 60

Resources:

  DevNS:
    Description: "Dev NS Record"
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub dev.${HostedZone}
      Comment: "Dev NS Record"
      HostedZoneName: !Ref HostedZone
      ResourceRecords:
        - ns-1810.awsdns-34.co.uk
        - ns-1220.awsdns-24.org
        - ns-209.awsdns-26.com
        - ns-934.awsdns-52.net
      TTL: !Ref DefaultNSTTL
      Type: NS


